### ISSUE TITLE
Getting issue on field "cc_address": violates not-null constraint

### ISSUE THREAD

**Issue by nielsonsantana** [dstegelman/django-mail-queue#98] opened 2017-08-18 19:57 UTC
django.db.utils.IntegrityError: null value in column "cc_address" violates not-null constraint.

**Comment by dstegelman** [comment] 2017-08-19 13:46
When/How are you getting this error? Can you provide more detail?  TextFields should not need to be set to null=True

**Comment by nielsonsantana** [comment] 2017-08-19 16:07
It's is the code that I use to send email. I setted the version of django-mail-queue to 3.0.2, to not have more this issue.

```
def send_email_mailqueue(mail_template="", mail_app="", context=""):
    new_message = MailerMessage()
    new_message.subject = context.get("subject", '')

    if context.get("reply_to", ''):
        new_message.reply_to = context.get("reply_to", '')
    if context.get('to_address', ''):
        new_message.to_address = context.get('to_address', '')
    if context.get('bcc_address', ''):
        new_message.bcc_address = context.get('bcc_address', '')
    new_message.from_address = settings.DEFAULT_FROM_EMAIL
    html_content = get_template(mail_template).render(
        context
    )
    html_content = Template(html_content).render(context)
    new_message.html_content = html_content
    new_message.app = mail_app
    new_message.save()

```

**Comment by dstegelman** [comment] 2017-08-20 21:17
Thanks for the feedback. Going to setup a test environment to check this out.

**Comment by dstegelman** [comment] 2017-08-20 23:55
Hi @nielsonsantana 

I started a brand new Django install and installed mail queue 3.1.0 and was unable to reproduce this issue when saving a new object.

This could likely be caused by a different issue, perhaps in the way the DB is configured or somewhere else in your code.  

I'm going to close this issue and the associated PR for now.  If others can re-produce or another user also reports this issue I can look into it further with additional information.

**Closed by dstegelman** 2017-08-20 23:55 UTC
